### PR TITLE
Fix error with laster ZfcUser

### LINKED ISSUE #51: Fatal with lastets zfcUser
Got this error when using the latest version of this module and the zfcUser

Catchable fatal error: Argument 1 passed to ZfcUser\Mapper\UserHydrator::__construct() must be an instance of Zend\Crypt\Password\PasswordInterface, none given, called in D:\Dropbox\server\Workspace\True-Life\vendor\danielss89\zfc-user-admin\config\services.config.php on line 92 and defined in D:\Dropbox\server\Workspace\True-Life\vendor\zf-commons\zfc-user\src\ZfcUser\Mapper\UserHydrator.php on line 21

### PR DESCRIPTION
**Pull request by stijnhau**
fix #51

### CODE REVIEW

**Comment by mtcocktail** [comment]
Works for me.

**Comment by stijnhau** [comment]
Indead can be even better by using DI and retriving the correct istance from the servie manager but then the zfcUser module needs to have that option.
So currenlty this is the best way (according to my opinion)

**Comment by Danielss89** [comment]
Can you rebase this? is it still a problem

**Comment by stijnhau** [comment]
Same issue as
https://github.com/Danielss89/ZfcUserAdmin/pull/48

**Pull request closed without merging**
