### PR TITLE
UserHydrator compatibility with ZfcUser module

### PR DESCRIPTION
**Pull request by keepanitreel**

### CODE REVIEW

**Comment by agustincl** [comment]
Works for me, but need add 
use Zend\Crypt\Password\Bcrypt;

**Comment by keepanitreel** [comment]
Yeah that's what happens when you edit files directly via github. :(

**Comment by stijnhau** [comment]
Not a bad fiox but i trhink https://github.com/Danielss89/ZfcUserAdmin/pull/55 is better because if they change it later to usa an other in stead of bcrupt we can get it correctly without changes needed to this module.

**Comment by stijnhau** [comment]
This should be closed.(fix of #55 already merged)(1 hour ago)

**Comment by Danielss89** [comment]
FIxed in another PR

**Pull request closed without merging**
